client:
	g++ -o client client.cpp

client_test:
	g++ -o client_test client.cpp client_test.cpp

client_test_file_transfer:
	g++ -o client_test_file_transfer client.cpp client_test_file_transfer.cpp

client_test_large_transfer:
	g++ -o client_test_large_transfer client.cpp client_test_large_transfer.cpp

client_test_id_transfer:
	g++ -o client_test_id_transfer client.cpp client_test_id_transfer.cpp

clean:
	rm -f client && rm -f client_test && rm -f client_test_file_transfer